### ISSUE TITLE
AttributeError: 'Document' object has no attribute 'get_location'

### ISSUE THREAD

**Issue by yochananmarqos** [maoschanz/gedit-plugin-open-as-root#4]
Using gedit 40.1 on GNOME 41.2 with Python 3.10.1 and GObject 3.42.0:

```
❯ gedit

(gedit:457309): GtkSourceView-WARNING **: 11:03:47.262: no color named ''
Traceback (most recent call last):
  File "/home/yochanan/.local/share/gedit/plugins/open_as_root.py", line 46, in update_item_state
    if self.window.get_active_document() is None or self.window.get_active_document().get_location() is None:
AttributeError: 'Document' object has no attribute 'get_location'
Traceback (most recent call last):
  File "/home/yochanan/.local/share/gedit/plugins/open_as_root.py", line 46, in update_item_state
    if self.window.get_active_document() is None or self.window.get_active_document().get_location() is None:
AttributeError: 'Document' object has no attribute 'get_location'
Traceback (most recent call last):
  File "/home/yochanan/.local/share/gedit/plugins/open_as_root.py", line 46, in update_item_state
    if self.window.get_active_document() is None or self.window.get_active_document().get_location() is None:
AttributeError: 'Document' object has no attribute 'get_location'
Traceback (most recent call last):
  File "/home/yochanan/.local/share/gedit/plugins/open_as_root.py", line 46, in update_item_state
    if self.window.get_active_document() is None or self.window.get_active_document().get_location() is None:
AttributeError: 'Document' object has no attribute 'get_location'
Traceback (most recent call last):
  File "/home/yochanan/.local/share/gedit/plugins/open_as_root.py", line 46, in update_item_state
    if self.window.get_active_document() is None or self.window.get_active_document().get_location() is None:
AttributeError: 'Document' object has no attribute 'get_location'
Traceback (most recent call last):
  File "/usr/lib/gedit/plugins/git/viewactivatable.py", line 113, in update_location
    self.location = self.buffer.get_file().get_location()
AttributeError: 'NoneType' object has no attribute 'get_file'

(gedit:457309): Gtk-CRITICAL **: 11:03:47.433: gtk_text_buffer_get_selection_bounds: assertion 'GTK_IS_TEXT_BUFFER (buffer)' failed
Traceback (most recent call last):
  File "/home/yochanan/.local/share/gedit/plugins/open_as_root.py", line 46, in update_item_state
    if self.window.get_active_document() is None or self.window.get_active_document().get_location() is None:
AttributeError: 'Document' object has no attribute 'get_location'
Traceback (most recent call last):
  File "/home/yochanan/.local/share/gedit/plugins/open_as_root.py", line 46, in update_item_state
    if self.window.get_active_document() is None or self.window.get_active_document().get_location() is None:
AttributeError: 'Document' object has no attribute 'get_location'

```

**Comment by maoschanz** [comment]
This plugin doesn't work for Gedit 40/41/42 for another reason already reported as #3, but my line 46 has nothing to do with it, since it doesn't contain at all the code in your error message: I fixed this API change more than 2 years ago.

You're either using an extremely outdated version of the code, or using a similar plugin by someone else

**Comment by yochananmarqos** [comment]
Ah, you're right. Sorry for the bother.
